import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'

const domain = process.env.NEXT_PUBLIC_APP_DOMAIN

export const metadata: Metadata = {
   title: 'HQPaint General Construction LLC',
   description: 'Generated by create next app',
   icons: {
      icon: [
         {
            rel: 'icon',
            type: 'image/png',
            media: '(prefers-color-scheme: light)',
            url: '/logo.png',
         },
         {
            rel: 'icon',
            type: 'image/png',
            media: '(prefers-color-scheme: dark)',
            url: '/logo-dark.png',
         },
      ],
   },
   metadataBase: new URL(domain || 'http://localhost:3000'),
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>
      </html>
   )
}
