import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'

export const metadata: Metadata = {
   title: 'HQPaint General Construction',
   description: 'Generated by create next app',
   icons: {
      icon: [
         {
            media: '(prefers-color-scheme: light)',
            url: '/logo.svg',
            href: '/logo.svg',
         },
         {
            media: '(prefers-color-scheme: dark)',
            url: '/logo.svg',
            href: '/logo.svg',
         },
      ],
   },
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>
      </html>
   )
}
